package org.pk.edog.seeder;

import org.pk.edog.model.custom.RangeObject;
import org.pk.edog.model.entity.Dog;
import org.pk.edog.model.enums.*;
import org.pk.edog.repository.DogRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public class DogSeeder implements CommandLineRunner {

    private final DogRepository dogRepository;

    public DogSeeder(DogRepository dogRepository) {
        this.dogRepository = dogRepository;
    }

    @Override
    public void run(String... args) {
        dogRepository.deleteAll();

        List<Dog> dogs = List.of(
                Dog.builder()
                        .breed(Breed.LABRADOR_RETRIEVER)
                        .shortDescription("Przyjazny i towarzyski")
                        .description("Labrador Retriever to przyjazna i towarzyska rasa.")
                        .imageUrl("https://png.pngtree.com/png-vector/20230922/ourmid/pngtree-labrador-retriever-dog-ai-generated-png-image_10144580.png")
                        .originCountry("Kanada")
                        .height(55.0f)
                        .weight(30.0f)
                        .lifeSpan(new RangeObject(15, 18))
                        .price(new RangeObject(3000, 4000))
                        .colors(List.of(Color.BLACK, Color.CREAM, Color.WHITE))
                        .characteristics(List.of(Characteristic.FRIENDLY, Characteristic.ENERGETIC,
                                Characteristic.CONFIDENT, Characteristic.PLAYFUL))
                        .breedingDifficulty(Difficulty.BEGINNER)
                        .activityLevel(Level.HIGH)
                        .sheddingLevel(Level.MEDIUM)
                        .spaceNeeds(Level.MEDIUM)
                        .groomingNeeds(Level.LOW)
                        .healthIssues(Level.MEDIUM)
                        .trainability(Level.HIGH)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.GERMAN_SHEPHERD)
                        .shortDescription("Pewny siebie i odważny")
                        .description("Owczarek niemiecki to pewna siebie i odważna rasa.")
                        .imageUrl("https://static.vecteezy.com/system/resources/thumbnails/027/247/020/small_2x/german-shepherd-dog-isolated-on-transparent-background-ai-generated-png.png")
                        .originCountry("Niemcy")
                        .height(60.0f)
                        .weight(35.0f)
                        .lifeSpan(new RangeObject(14, 18))
                        .price(new RangeObject(2000, 3000))
                        .colors(List.of(Color.BLACK, Color.TAN, Color.SABLE))
                        .characteristics(List.of(Characteristic.CONFIDENT, Characteristic.INTELLIGENT,
                                Characteristic.ACTIVE, Characteristic.ENERGETIC))
                        .breedingDifficulty(Difficulty.BEGINNER)
                        .activityLevel(Level.HIGH)
                        .sheddingLevel(Level.HIGH)
                        .spaceNeeds(Level.HIGH)
                        .groomingNeeds(Level.MEDIUM)
                        .healthIssues(Level.HIGH)
                        .trainability(Level.HIGH)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.GOLDEN_RETRIEVER)
                        .shortDescription("Inteligentny i przyjazny")
                        .description("Golden Retriever to inteligentna i przyjazna rasa.")
                        .imageUrl("https://png.pngtree.com/png-vector/20240208/ourmid/pngtree-cute-golden-retriever-dog-png-image_11717250.png")
                        .originCountry("Szkocja")
                        .height(55.0f)
                        .weight(30.0f)
                        .lifeSpan(new RangeObject(16, 18))
                        .price(new RangeObject(2500, 3500))
                        .colors(List.of(Color.GOLDEN))
                        .characteristics(List.of(Characteristic.INTELLIGENT, Characteristic.FRIENDLY, Characteristic.ACTIVE))
                        .breedingDifficulty(Difficulty.INTERMEDIATE)
                        .activityLevel(Level.HIGH)
                        .sheddingLevel(Level.HIGH)
                        .spaceNeeds(Level.MEDIUM)
                        .groomingNeeds(Level.MEDIUM)
                        .healthIssues(Level.MEDIUM)
                        .trainability(Level.HIGH)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.FRENCH_BULLDOG)
                        .shortDescription("Grzeczny i zabawny")
                        .description("Buldog francuski jest zabawną i łatwą w hodowli rasą")
                        .imageUrl("https://static.vecteezy.com/system/resources/thumbnails/024/509/185/small_2x/french-bulldog-isolated-on-background-with-generative-ai-png.png")
                        .originCountry("Francja")
                        .height(30.0f)
                        .weight(12.0f)
                        .lifeSpan(new RangeObject(12, 16))
                        .price(new RangeObject(2500, 4000))
                        .colors(List.of(Color.BRINDLE, Color.FAWN, Color.TRI_COLOR))
                        .characteristics(List.of(Characteristic.CALM, Characteristic.PLAYFUL, Characteristic.SHY,
                                Characteristic.GENTLE))
                        .breedingDifficulty(Difficulty.ADVANCED)
                        .activityLevel(Level.LOW)
                        .sheddingLevel(Level.LOW)
                        .spaceNeeds(Level.LOW)
                        .groomingNeeds(Level.LOW)
                        .healthIssues(Level.HIGH)
                        .trainability(Level.MEDIUM)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.BULLDOG)
                        .shortDescription("Potulny i chętny do działania")
                        .description("Buldog to potulna i pełna chęci do działania rasa.")
                        .imageUrl("https://png.pngtree.com/png-clipart/20230411/original/pngtree-dog-bulldog-transparent-on-white-png-image_9044452.png")
                        .originCountry("Anglia")
                        .height(40.0f)
                        .weight(25.0f)
                        .lifeSpan(new RangeObject(16, 18))
                        .price(new RangeObject(2000, 3000))
                        .colors(List.of(Color.BRINDLE, Color.WHITE))
                        .characteristics(List.of(Characteristic.PROTECTIVE, Characteristic.ALERT,
                                Characteristic.CONFIDENT))
                        .breedingDifficulty(Difficulty.ADVANCED)
                        .activityLevel(Level.LOW)
                        .sheddingLevel(Level.MEDIUM)
                        .spaceNeeds(Level.LOW)
                        .groomingNeeds(Level.LOW)
                        .healthIssues(Level.HIGH)
                        .trainability(Level.MEDIUM)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.POODLE)
                        .shortDescription("Aktywny i czujny")
                        .description("Pudel to aktywna i czujna rasa.")
                        .imageUrl("https://png.pngtree.com/png-clipart/20230506/original/pngtree-isolated-poodle-dog-on-transparent-png-image_9145520.png")
                        .originCountry("Niemcy")
                        .height(45.0f)
                        .weight(20.0f)
                        .lifeSpan(new RangeObject(16, 20))
                        .price(new RangeObject(2000, 5000))
                        .colors(List.of(Color.WHITE, Color.BLACK, Color.BROWN))
                        .characteristics(List.of(Characteristic.ACTIVE, Characteristic.ALERT,
                                Characteristic.PLAYFUL, Characteristic.INTELLIGENT))
                        .breedingDifficulty(Difficulty.BEGINNER)
                        .activityLevel(Level.HIGH)
                        .sheddingLevel(Level.LOW)
                        .spaceNeeds(Level.MEDIUM)
                        .groomingNeeds(Level.HIGH)
                        .healthIssues(Level.MEDIUM)
                        .trainability(Level.HIGH)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(true)
                        .build(),
                Dog.builder()
                        .breed(Breed.BEAGLE)
                        .shortDescription("Ciekawski i wesoły")
                        .description("Beagle to ciekawska i wesoła rasa.")
                        .imageUrl("https://static.vecteezy.com/system/resources/previews/042/056/161/non_2x/ai-generated-playful-beagle-dog-on-transparent-background-curious-dog-cutout-free-png.png")
                        .originCountry("Anglia")
                        .height(35.0f)
                        .weight(15.0f)
                        .lifeSpan(new RangeObject(14, 18))
                        .price(new RangeObject(2000, 4000))
                        .colors(List.of(Color.FAWN))
                        .characteristics(List.of(Characteristic.CURIOUS, Characteristic.CALM,
                                Characteristic.CONFIDENT, Characteristic.FRIENDLY))
                        .breedingDifficulty(Difficulty.INTERMEDIATE)
                        .activityLevel(Level.HIGH)
                        .sheddingLevel(Level.MEDIUM)
                        .spaceNeeds(Level.MEDIUM)
                        .groomingNeeds(Level.LOW)
                        .healthIssues(Level.MEDIUM)
                        .trainability(Level.HIGH)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.ROTTWEILER)
                        .shortDescription("Lojalny i pewny siebie")
                        .description("Rottweiler to lojalna i pewna siebie rasa.")
                        .imageUrl("https://png.pngtree.com/png-vector/20240101/ourmid/pngtree-rottweiler-dog-sitting-and-looking-up-isolated-on-white-png-image_11390967.png")
                        .originCountry("Niemcy")
                        .height(65.0f)
                        .weight(50.0f)
                        .lifeSpan(new RangeObject(15, 18))
                        .price(new RangeObject(3000, 6000))
                        .colors(List.of(Color.BLACK, Color.TAN))
                        .characteristics(List.of(Characteristic.LOYAL, Characteristic.CONFIDENT, Characteristic.ACTIVE,
                                Characteristic.STUBBORN, Characteristic.PROTECTIVE))
                        .breedingDifficulty(Difficulty.INTERMEDIATE)
                        .activityLevel(Level.HIGH)
                        .sheddingLevel(Level.HIGH)
                        .spaceNeeds(Level.HIGH)
                        .groomingNeeds(Level.MEDIUM)
                        .healthIssues(Level.HIGH)
                        .trainability(Level.HIGH)
                        .goodWithChildren(false)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.DACHSHUND)
                        .shortDescription("Żywy i odważny")
                        .description("Jamnik to żywa i odważna rasa.")
                        .imageUrl("https://pngimg.com/d/dachshund_PNG34.png")
                        .originCountry("Niemcy")
                        .height(25.0f)
                        .weight(10.0f)
                        .lifeSpan(new RangeObject(14, 18))
                        .price(new RangeObject(1500, 4000))
                        .colors(List.of(Color.BLACK, Color.TAN))
                        .characteristics(List.of(Characteristic.ENERGETIC, Characteristic.PLAYFUL,
                                Characteristic.STUBBORN, Characteristic.ALERT))
                        .breedingDifficulty(Difficulty.INTERMEDIATE)
                        .activityLevel(Level.MEDIUM)
                        .sheddingLevel(Level.LOW)
                        .spaceNeeds(Level.LOW)
                        .groomingNeeds(Level.LOW)
                        .healthIssues(Level.MEDIUM)
                        .trainability(Level.HIGH)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.PEMBROKE_WELSH_CORGI)
                        .shortDescription("Pogodny i przyjacielski")
                        .description("Pembroke Welsh Corgi to pogodna i przyjacielska rasa psa.")
                        .imageUrl("https://png.pngtree.com/png-vector/20230318/ourmid/pngtree-dog-corgi-short-legged-animal-transparent-on-white-background-png-image_6655763.png")
                        .originCountry("Walia")
                        .height(30.0f)
                        .weight(12.0f)
                        .lifeSpan(new RangeObject(12, 15))
                        .price(new RangeObject(2500, 3500))
                        .colors(List.of(Color.RED, Color.WHITE))
                        .characteristics(List.of(Characteristic.INTELLIGENT, Characteristic.PLAYFUL, Characteristic.FRIENDLY))
                        .breedingDifficulty(Difficulty.INTERMEDIATE)
                        .activityLevel(Level.MEDIUM)
                        .sheddingLevel(Level.HIGH)
                        .spaceNeeds(Level.MEDIUM)
                        .groomingNeeds(Level.LOW)
                        .healthIssues(Level.MEDIUM)
                        .trainability(Level.HIGH)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.SIBERIAN_HUSKY)
                        .shortDescription("Energiczny i przyjacielski")
                        .description("Syberyjski Husky to energiczna i przyjacielska rasa psa.")
                        .imageUrl("https://static.vecteezy.com/system/resources/previews/027/296/608/non_2x/siberian-husky-dog-breed-transparent-background-free-png.png")
                        .originCountry("Rosja")
                        .height(55.0f)
                        .weight(23.0f)
                        .lifeSpan(new RangeObject(12, 14))
                        .price(new RangeObject(3000, 4000))
                        .colors(List.of(Color.WHITE, Color.BLACK))
                        .characteristics(List.of(Characteristic.ACTIVE, Characteristic.FRIENDLY, Characteristic.ENERGETIC))
                        .breedingDifficulty(Difficulty.ADVANCED)
                        .activityLevel(Level.HIGH)
                        .sheddingLevel(Level.HIGH)
                        .spaceNeeds(Level.HIGH)
                        .groomingNeeds(Level.MEDIUM)
                        .healthIssues(Level.MEDIUM)
                        .trainability(Level.MEDIUM)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.GREAT_DANE)
                        .shortDescription("Łagodny olbrzym")
                        .description("Dog niemiecki to łagodny i majestatyczny olbrzym.")
                        .imageUrl("https://static.vecteezy.com/system/resources/previews/047/553/719/non_2x/great-dane-dog-standing-isolated-from-background-free-png.png")
                        .originCountry("Niemcy")
                        .height(80.0f)
                        .weight(70.0f)
                        .lifeSpan(new RangeObject(8, 10))
                        .price(new RangeObject(4000, 6000))
                        .colors(List.of(Color.BLACK, Color.WHITE, Color.BLUE))
                        .characteristics(List.of(Characteristic.GENTLE, Characteristic.FRIENDLY, Characteristic.LOYAL))
                        .breedingDifficulty(Difficulty.INTERMEDIATE)
                        .activityLevel(Level.MEDIUM)
                        .sheddingLevel(Level.MEDIUM)
                        .spaceNeeds(Level.HIGH)
                        .groomingNeeds(Level.LOW)
                        .healthIssues(Level.HIGH)
                        .trainability(Level.HIGH)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.DOBERMAN_PINSCHER)
                        .shortDescription("Lojalny i czujny")
                        .description("Doberman to lojalna i czujna rasa psa.")
                        .imageUrl("https://png.pngtree.com/png-clipart/20230429/ourmid/pngtree-doberman-isolated-dog-on-white-background-png-image_6746736.png")
                        .originCountry("Niemcy")
                        .height(65.0f)
                        .weight(40.0f)
                        .lifeSpan(new RangeObject(10, 12))
                        .price(new RangeObject(3500, 5000))
                        .colors(List.of(Color.BLACK, Color.TAN))
                        .characteristics(List.of(Characteristic.PROTECTIVE, Characteristic.CONFIDENT, Characteristic.ACTIVE))
                        .breedingDifficulty(Difficulty.ADVANCED)
                        .activityLevel(Level.HIGH)
                        .sheddingLevel(Level.MEDIUM)
                        .spaceNeeds(Level.MEDIUM)
                        .groomingNeeds(Level.LOW)
                        .healthIssues(Level.MEDIUM)
                        .trainability(Level.HIGH)
                        .goodWithChildren(true)
                        .goodWithOtherPets(false)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.AUSTRALIAN_SHEPHERD)
                        .shortDescription("Inteligentny i pracowity")
                        .description("Owczarek australijski to inteligentna i pracowita rasa psa.")
                        .imageUrl("https://static.vecteezy.com/system/resources/previews/048/094/348/non_2x/a-full-length-australian-shepherd-dog-on-transparent-background-free-png.png")
                        .originCountry("Stany Zjednoczone")
                        .height(50.0f)
                        .weight(25.0f)
                        .lifeSpan(new RangeObject(12, 15))
                        .price(new RangeObject(3000, 4500))
                        .colors(List.of(Color.BLUE, Color.RED, Color.MERLE))
                        .characteristics(List.of(Characteristic.INTELLIGENT, Characteristic.ACTIVE, Characteristic.PLAYFUL))
                        .breedingDifficulty(Difficulty.INTERMEDIATE)
                        .activityLevel(Level.HIGH)
                        .sheddingLevel(Level.HIGH)
                        .spaceNeeds(Level.HIGH)
                        .groomingNeeds(Level.MEDIUM)
                        .healthIssues(Level.MEDIUM)
                        .trainability(Level.HIGH)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.SHIH_TZU)
                        .shortDescription("Towarzyski i czuły")
                        .description("Shih Tzu to towarzyska i czuła rasa psa.")
                        .imageUrl("https://png.pngtree.com/png-vector/20231016/ourmid/pngtree-brown-cue-shih-tzu-dog-animal-png-image_10186918.png")
                        .originCountry("Chiny")
                        .height(25.0f)
                        .weight(7.0f)
                        .lifeSpan(new RangeObject(10, 16))
                        .price(new RangeObject(2000, 4000))
                        .colors(List.of(Color.WHITE, Color.GOLDEN, Color.BROWN))
                        .characteristics(List.of(Characteristic.CALM, Characteristic.GENTLE, Characteristic.FRIENDLY))
                        .breedingDifficulty(Difficulty.BEGINNER)
                        .activityLevel(Level.LOW)
                        .sheddingLevel(Level.LOW)
                        .spaceNeeds(Level.LOW)
                        .groomingNeeds(Level.HIGH)
                        .healthIssues(Level.MEDIUM)
                        .trainability(Level.MEDIUM)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(true)
                        .build(),
                Dog.builder()
                        .breed(Breed.MINIATURE_SCHNAUZER)
                        .shortDescription("Czujny i inteligentny")
                        .description("Miniaturowy sznaucer to czujna i inteligentna rasa psa.")
                        .imageUrl("https://static.vecteezy.com/system/resources/thumbnails/036/496/539/small_2x/ai-generated-a-miniature-schnauzer-dog-sitting-on-trasparent-background-png.png")
                        .originCountry("Niemcy")
                        .height(35.0f)
                        .weight(8.0f)
                        .lifeSpan(new RangeObject(12, 15))
                        .price(new RangeObject(2000, 3500))
                        .colors(List.of(Color.BLACK, Color.GREY))
                        .characteristics(List.of(Characteristic.ACTIVE, Characteristic.FRIENDLY, Characteristic.INTELLIGENT))
                        .breedingDifficulty(Difficulty.INTERMEDIATE)
                        .activityLevel(Level.MEDIUM)
                        .sheddingLevel(Level.LOW)
                        .spaceNeeds(Level.MEDIUM)
                        .groomingNeeds(Level.HIGH)
                        .healthIssues(Level.MEDIUM)
                        .trainability(Level.HIGH)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(true)
                        .build(),
                Dog.builder()
                        .breed(Breed.CAVALIER_KING_CHARLES_SPANIEL)
                        .shortDescription("Czuły i delikatny")
                        .description("Cavalier King Charles Spaniel to czuła i delikatna rasa psa.")
                        .imageUrl("https://static.vecteezy.com/system/resources/thumbnails/047/843/951/small_2x/cavalier-king-charles-spaniel-dog-sitting-on-a-transparent-background-png.png")
                        .originCountry("Anglia")
                        .height(30.0f)
                        .weight(8.0f)
                        .lifeSpan(new RangeObject(10, 15))
                        .price(new RangeObject(2500, 4000))
                        .colors(List.of(Color.RED, Color.WHITE))
                        .characteristics(List.of(Characteristic.GENTLE, Characteristic.FRIENDLY, Characteristic.PLAYFUL))
                        .breedingDifficulty(Difficulty.INTERMEDIATE)
                        .activityLevel(Level.LOW)
                        .sheddingLevel(Level.MEDIUM)
                        .spaceNeeds(Level.LOW)
                        .groomingNeeds(Level.MEDIUM)
                        .healthIssues(Level.MEDIUM)
                        .trainability(Level.HIGH)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.CHIHUAHUA)
                        .shortDescription("Mały, ale odważny")
                        .description("Chihuahua to malutka rasa psa, znana ze swojego odwagi i energii.")
                        .imageUrl("https://static.vecteezy.com/system/resources/previews/035/940/131/non_2x/ai-generated-chihuahua-isolated-on-transparent-background-free-png.png")
                        .originCountry("Meksyk")
                        .height(15.0f)
                        .weight(2.5f)
                        .lifeSpan(new RangeObject(12, 20))
                        .price(new RangeObject(2000, 3500))
                        .colors(List.of(Color.TAN, Color.BLACK, Color.WHITE))
                        .characteristics(List.of(Characteristic.PROTECTIVE, Characteristic.ENERGETIC, Characteristic.LOYAL))
                        .breedingDifficulty(Difficulty.BEGINNER)
                        .activityLevel(Level.LOW)
                        .sheddingLevel(Level.LOW)
                        .spaceNeeds(Level.LOW)
                        .groomingNeeds(Level.LOW)
                        .healthIssues(Level.HIGH)
                        .trainability(Level.MEDIUM)
                        .goodWithChildren(false)
                        .goodWithOtherPets(false)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.MALTESE)
                        .shortDescription("Uroczy i delikatny")
                        .description("Maltese to mała, delikatna rasa psa o długim białym futrze.")
                        .imageUrl("https://png.pngtree.com/png-clipart/20230321/ourmid/pngtree-a-cute-white-maltese-pet-puppy-png-image_6657423.png")
                        .originCountry("Malta")
                        .height(20.0f)
                        .weight(4.0f)
                        .lifeSpan(new RangeObject(12, 15))
                        .price(new RangeObject(3000, 5000))
                        .colors(List.of(Color.WHITE))
                        .characteristics(List.of(Characteristic.GENTLE, Characteristic.FRIENDLY, Characteristic.PLAYFUL))
                        .breedingDifficulty(Difficulty.INTERMEDIATE)
                        .activityLevel(Level.LOW)
                        .sheddingLevel(Level.LOW)
                        .spaceNeeds(Level.LOW)
                        .groomingNeeds(Level.HIGH)
                        .healthIssues(Level.MEDIUM)
                        .trainability(Level.HIGH)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(true)
                        .build(),
                Dog.builder()
                        .breed(Breed.BOSTON_TERRIER)
                        .shortDescription("Energiczny i wesoły")
                        .description("Boston Terrier to energiczna rasa psa o charakterystycznym czarno-białym umaszczeniu.")
                        .imageUrl("https://png.pngtree.com/png-vector/20231117/ourmid/pngtree-relaxed-rester-cavalier-king-boston-terrier-sitting-on-white-png-image_10627022.png")
                        .originCountry("USA")
                        .height(40.0f)
                        .weight(10.0f)
                        .lifeSpan(new RangeObject(11, 15))
                        .price(new RangeObject(2500, 4000))
                        .colors(List.of(Color.BLACK, Color.WHITE))
                        .characteristics(List.of(Characteristic.PLAYFUL, Characteristic.FRIENDLY, Characteristic.INTELLIGENT))
                        .breedingDifficulty(Difficulty.BEGINNER)
                        .activityLevel(Level.MEDIUM)
                        .sheddingLevel(Level.LOW)
                        .spaceNeeds(Level.MEDIUM)
                        .groomingNeeds(Level.LOW)
                        .healthIssues(Level.HIGH)
                        .trainability(Level.HIGH)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.SHIBA_INU)
                        .shortDescription("Niezależny i czujny")
                        .description("Shiba Inu to niezależna rasa psa pochodząca z Japonii, znana z czujności i czystego charakteru.")
                        .imageUrl("https://preview.redd.it/fsjzfkzxk6a71.png?width=1080&crop=smart&auto=webp&s=98a87d34baff5624c1782777492ef0c97ddbfb86")
                        .originCountry("Japonia")
                        .height(40.0f)
                        .weight(10.0f)
                        .lifeSpan(new RangeObject(12, 16))
                        .price(new RangeObject(4000, 6000))
                        .colors(List.of(Color.RED, Color.BLACK, Color.WHITE))
                        .characteristics(List.of(Characteristic.ALERT, Characteristic.INDEPENDENT, Characteristic.STUBBORN))
                        .breedingDifficulty(Difficulty.INTERMEDIATE)
                        .activityLevel(Level.MEDIUM)
                        .sheddingLevel(Level.HIGH)
                        .spaceNeeds(Level.MEDIUM)
                        .groomingNeeds(Level.MEDIUM)
                        .healthIssues(Level.LOW)
                        .trainability(Level.MEDIUM)
                        .goodWithChildren(true)
                        .goodWithOtherPets(false)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.BORDER_COLLIE)
                        .shortDescription("Inteligentny i pracowity")
                        .description("Border Collie to niezwykle inteligentna rasa psa, idealna do pracy i aktywności.")
                        .imageUrl("https://static.vecteezy.com/system/resources/thumbnails/027/247/023/small_2x/border-collie-dog-isolated-on-transparent-background-ai-generated-png.png")
                        .originCountry("Wielka Brytania")
                        .height(50.0f)
                        .weight(20.0f)
                        .lifeSpan(new RangeObject(12, 15))
                        .price(new RangeObject(3000, 5000))
                        .colors(List.of(Color.BLACK, Color.WHITE, Color.RED))
                        .characteristics(List.of(Characteristic.INTELLIGENT, Characteristic.ENERGETIC, Characteristic.LOYAL))
                        .breedingDifficulty(Difficulty.ADVANCED)
                        .activityLevel(Level.HIGH)
                        .sheddingLevel(Level.MEDIUM)
                        .spaceNeeds(Level.HIGH)
                        .groomingNeeds(Level.MEDIUM)
                        .healthIssues(Level.MEDIUM)
                        .trainability(Level.HIGH)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.BICHON_FRISE)
                        .shortDescription("Radosny i towarzyski")
                        .description("Bichon Frise to mały, towarzyski pies o kręconym, białym futrze.")
                        .imageUrl("https://png.pngtree.com/png-vector/20231120/ourmid/pngtree-bichon-frise-purebred-png-image_10573248.png")
                        .originCountry("Francja")
                        .height(28.0f)
                        .weight(6.0f)
                        .lifeSpan(new RangeObject(12, 15))
                        .price(new RangeObject(3000, 5000))
                        .colors(List.of(Color.WHITE))
                        .characteristics(List.of(Characteristic.FRIENDLY, Characteristic.AFFECTIONATE, Characteristic.CHEERFUL))
                        .breedingDifficulty(Difficulty.BEGINNER)
                        .activityLevel(Level.LOW)
                        .sheddingLevel(Level.LOW)
                        .spaceNeeds(Level.LOW)
                        .groomingNeeds(Level.HIGH)
                        .healthIssues(Level.MEDIUM)
                        .trainability(Level.HIGH)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(true)
                        .build(),
                Dog.builder()
                        .breed(Breed.AKITA)
                        .shortDescription("Lojalny i odważny")
                        .description("Akita to duży pies o imponującym wyglądzie, znany z lojalności i odwagi.")
                        .imageUrl("https://png.pngtree.com/png-vector/20230918/ourmid/pngtree-3d-akita-dog-png-image_10129183.png")
                        .originCountry("Japonia")
                        .height(67.0f)
                        .weight(50.0f)
                        .lifeSpan(new RangeObject(10, 13))
                        .price(new RangeObject(4000, 7000))
                        .colors(List.of(Color.RED, Color.WHITE, Color.BLACK))
                        .characteristics(List.of(Characteristic.BRAVE, Characteristic.LOYAL, Characteristic.INDEPENDENT))
                        .breedingDifficulty(Difficulty.ADVANCED)
                        .activityLevel(Level.MEDIUM)
                        .sheddingLevel(Level.HIGH)
                        .spaceNeeds(Level.HIGH)
                        .groomingNeeds(Level.MEDIUM)
                        .healthIssues(Level.MEDIUM)
                        .trainability(Level.MEDIUM)
                        .goodWithChildren(true)
                        .goodWithOtherPets(false)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.BELGIAN_MALINOIS)
                        .shortDescription("Zwinny i pracowity")
                        .description("Belgian Malinois to pies o dużej energii, idealny do pracy i zadań specjalnych.")
                        .imageUrl("https://crazydoglady.net.au/cdn/shop/files/BelgianMal_1_300x300.png?v=1697012482")
                        .originCountry("Belgia")
                        .height(62.0f)
                        .weight(28.0f)
                        .lifeSpan(new RangeObject(12, 14))
                        .price(new RangeObject(3000, 5000))
                        .colors(List.of(Color.FAWN, Color.BLACK))
                        .characteristics(List.of(Characteristic.ENERGETIC, Characteristic.INTELLIGENT, Characteristic.LOYAL))
                        .breedingDifficulty(Difficulty.ADVANCED)
                        .activityLevel(Level.HIGH)
                        .sheddingLevel(Level.MEDIUM)
                        .spaceNeeds(Level.HIGH)
                        .groomingNeeds(Level.MEDIUM)
                        .healthIssues(Level.LOW)
                        .trainability(Level.HIGH)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.WEIMARANER)
                        .shortDescription("Energiczny i inteligentny")
                        .description("Weimaraner to elegancki, energiczny pies myśliwski o srebrnym umaszczeniu.")
                        .imageUrl("https://png.pngtree.com/png-vector/20231019/ourmid/pngtree-portrait-of-sitting-weimaraner-png-image_10253980.png")
                        .originCountry("Niemcy")
                        .height(63.0f)
                        .weight(30.0f)
                        .lifeSpan(new RangeObject(11, 13))
                        .price(new RangeObject(4000, 6000))
                        .colors(List.of(Color.GREY))
                        .characteristics(List.of(Characteristic.ENERGETIC, Characteristic.INTELLIGENT, Characteristic.LOYAL))
                        .breedingDifficulty(Difficulty.ADVANCED)
                        .activityLevel(Level.HIGH)
                        .sheddingLevel(Level.MEDIUM)
                        .spaceNeeds(Level.HIGH)
                        .groomingNeeds(Level.LOW)
                        .healthIssues(Level.MEDIUM)
                        .trainability(Level.HIGH)
                        .goodWithChildren(true)
                        .goodWithOtherPets(false)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.NEWFOUNDLAND)
                        .shortDescription("Gigantyczny i łagodny")
                        .description("Newfoundland to duży pies wodny znany ze swojej siły i łagodnego charakteru.")
                        .imageUrl("https://png.pngtree.com/png-vector/20231023/ourmid/pngtree-puppy-newfoundland-dog-isolated-png-image_10174502.png")
                        .originCountry("Kanada")
                        .height(70.0f)
                        .weight(68.0f)
                        .lifeSpan(new RangeObject(8, 10))
                        .price(new RangeObject(4000, 7000))
                        .colors(List.of(Color.BLACK, Color.BROWN, Color.WHITE))
                        .characteristics(List.of(Characteristic.GENTLE, Characteristic.LOYAL, Characteristic.FRIENDLY))
                        .breedingDifficulty(Difficulty.ADVANCED)
                        .activityLevel(Level.MEDIUM)
                        .sheddingLevel(Level.HIGH)
                        .spaceNeeds(Level.HIGH)
                        .groomingNeeds(Level.HIGH)
                        .healthIssues(Level.HIGH)
                        .trainability(Level.HIGH)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.SAINT_BERNARD)
                        .shortDescription("Łagodny gigant")
                        .description("Saint Bernard to potężny, łagodny pies znany z ratownictwa w górach.")
                        .imageUrl("https://static.vecteezy.com/system/resources/thumbnails/045/384/113/small_2x/saint-bernard-illustration-png.png")
                        .originCountry("Szwajcaria")
                        .height(75.0f)
                        .weight(70.0f)
                        .lifeSpan(new RangeObject(8, 10))
                        .price(new RangeObject(4000, 8000))
                        .colors(List.of(Color.BROWN, Color.WHITE))
                        .characteristics(List.of(Characteristic.GENTLE, Characteristic.LOYAL, Characteristic.CALM))
                        .breedingDifficulty(Difficulty.INTERMEDIATE)
                        .activityLevel(Level.MEDIUM)
                        .sheddingLevel(Level.HIGH)
                        .spaceNeeds(Level.HIGH)
                        .groomingNeeds(Level.MEDIUM)
                        .healthIssues(Level.HIGH)
                        .trainability(Level.MEDIUM)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.BASSET_HOUND)
                        .shortDescription("Uroczy i spokojny")
                        .description("Basset Hound to pies o długich uszach, znany z doskonałego węchu i spokojnej natury.")
                        .imageUrl("https://png.pngtree.com/png-vector/20240309/ourmid/pngtree-basset-hound-dog-looking-to-the-side-and-and-isolated-on-png-image_11907111.png")
                        .originCountry("Francja")
                        .height(35.0f)
                        .weight(25.0f)
                        .lifeSpan(new RangeObject(10, 12))
                        .price(new RangeObject(2500, 4000))
                        .colors(List.of(Color.BROWN, Color.WHITE, Color.BLACK))
                        .characteristics(List.of(Characteristic.FRIENDLY, Characteristic.CALM, Characteristic.STUBBORN))
                        .breedingDifficulty(Difficulty.INTERMEDIATE)
                        .activityLevel(Level.LOW)
                        .sheddingLevel(Level.MEDIUM)
                        .spaceNeeds(Level.MEDIUM)
                        .groomingNeeds(Level.LOW)
                        .healthIssues(Level.MEDIUM)
                        .trainability(Level.LOW)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.ALASKAN_MALAMUTE)
                        .shortDescription("Silny i wytrzymały")
                        .description("Alaskan Malamute to duży pies pracujący, znany z ciągnięcia sań w trudnych warunkach.")
                        .imageUrl("https://t4.ftcdn.net/jpg/05/82/88/31/360_F_582883105_BTvulbdrnzuq9a19AjsnUemFasCKr6Gn.png")
                        .originCountry("Stany Zjednoczone")
                        .height(65.0f)
                        .weight(45.0f)
                        .lifeSpan(new RangeObject(10, 14))
                        .price(new RangeObject(4000, 6000))
                        .colors(List.of(Color.GREY, Color.WHITE, Color.BLACK))
                        .characteristics(List.of(Characteristic.BRAVE, Characteristic.CONFIDENT, Characteristic.LOYAL))
                        .breedingDifficulty(Difficulty.ADVANCED)
                        .activityLevel(Level.HIGH)
                        .sheddingLevel(Level.HIGH)
                        .spaceNeeds(Level.HIGH)
                        .groomingNeeds(Level.MEDIUM)
                        .healthIssues(Level.MEDIUM)
                        .trainability(Level.MEDIUM)
                        .goodWithChildren(true)
                        .goodWithOtherPets(false)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.PUG)
                        .shortDescription("Zabawny i towarzyski")
                        .description("Pug to mały, zabawny pies o charakterystycznej zmarszczonej twarzy.")
                        .imageUrl("https://png.pngtree.com/png-vector/20240128/ourmid/pngtree-pug-dog-breed-png-image_11505821.png")
                        .originCountry("Chiny")
                        .height(30.0f)
                        .weight(7.0f)
                        .lifeSpan(new RangeObject(12, 15))
                        .price(new RangeObject(2000, 4000))
                        .colors(List.of(Color.FAWN, Color.BLACK))
                        .characteristics(List.of(Characteristic.FRIENDLY, Characteristic.PLAYFUL, Characteristic.AFFECTIONATE))
                        .breedingDifficulty(Difficulty.BEGINNER)
                        .activityLevel(Level.LOW)
                        .sheddingLevel(Level.MEDIUM)
                        .spaceNeeds(Level.LOW)
                        .groomingNeeds(Level.LOW)
                        .healthIssues(Level.HIGH)
                        .trainability(Level.MEDIUM)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.IRISH_SETTER)
                        .shortDescription("Pełen energii i elegancji")
                        .description("Irish Setter to energiczny pies myśliwski, znany z pięknego rudego umaszczenia.")
                        .imageUrl("https://wallpapers.com/images/hd/irish-setter-dog-png-xcb67-6pd3z2qjwlrnegg3.jpg")
                        .originCountry("Irlandia")
                        .height(67.0f)
                        .weight(32.0f)
                        .lifeSpan(new RangeObject(11, 15))
                        .price(new RangeObject(5000, 8000))
                        .colors(List.of(Color.RED))
                        .characteristics(List.of(Characteristic.ENERGETIC, Characteristic.FRIENDLY, Characteristic.INTELLIGENT))
                        .breedingDifficulty(Difficulty.INTERMEDIATE)
                        .activityLevel(Level.HIGH)
                        .sheddingLevel(Level.HIGH)
                        .spaceNeeds(Level.HIGH)
                        .groomingNeeds(Level.HIGH)
                        .healthIssues(Level.MEDIUM)
                        .trainability(Level.HIGH)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.BORZOI)
                        .shortDescription("Elegancki i spokojny")
                        .description("Borzoj, znany również jako wilczarz rosyjski, to elegancki i spokojny pies myśliwski.")
                        .imageUrl("https://static.wikia.nocookie.net/nicos-nextbots-fanmade/images/9/99/Borzoi.png/revision/latest/thumbnail/width/360/height/450?cb=20230127235155")
                        .originCountry("Rosja")
                        .height(75.0f)
                        .weight(40.0f)
                        .lifeSpan(new RangeObject(9, 14))
                        .price(new RangeObject(5000, 8000))
                        .colors(List.of(Color.WHITE, Color.TAN, Color.GREY))
                        .characteristics(List.of(Characteristic.GENTLE, Characteristic.CALM, Characteristic.LOYAL))
                        .breedingDifficulty(Difficulty.ADVANCED)
                        .activityLevel(Level.MEDIUM)
                        .sheddingLevel(Level.MEDIUM)
                        .spaceNeeds(Level.HIGH)
                        .groomingNeeds(Level.MEDIUM)
                        .healthIssues(Level.MEDIUM)
                        .trainability(Level.MEDIUM)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.STAFFORDSHIRE_BULL_TERRIER)
                        .shortDescription("Silny i lojalny")
                        .description("Staffordshire Bull Terrier to odważny i lojalny pies, znany ze swojej siły.")
                        .imageUrl("https://png.pngtree.com/png-clipart/20231017/original/pngtree-staffordshire-bull-terrier-isolated-photo-png-image_13335996.png")
                        .originCountry("Anglia")
                        .height(40.0f)
                        .weight(17.0f)
                        .lifeSpan(new RangeObject(12, 16))
                        .price(new RangeObject(3000, 6000))
                        .colors(List.of(Color.BLACK, Color.BROWN, Color.WHITE))
                        .characteristics(List.of(Characteristic.CONFIDENT, Characteristic.FRIENDLY, Characteristic.BRAVE))
                        .breedingDifficulty(Difficulty.INTERMEDIATE)
                        .activityLevel(Level.HIGH)
                        .sheddingLevel(Level.MEDIUM)
                        .spaceNeeds(Level.MEDIUM)
                        .groomingNeeds(Level.LOW)
                        .healthIssues(Level.MEDIUM)
                        .trainability(Level.HIGH)
                        .goodWithChildren(true)
                        .goodWithOtherPets(false)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.PAPILLON)
                        .shortDescription("Mały i inteligentny")
                        .description("Papillon to niewielki pies o inteligentnym i żywiołowym charakterze.")
                        .imageUrl("https://static.vecteezy.com/system/resources/previews/038/280/543/non_2x/ai-generated-papillon-dog-isolated-on-background-free-png.png")
                        .originCountry("Francja")
                        .height(28.0f)
                        .weight(4.0f)
                        .lifeSpan(new RangeObject(13, 16))
                        .price(new RangeObject(2000, 4000))
                        .colors(List.of(Color.WHITE, Color.BROWN, Color.BLACK))
                        .characteristics(List.of(Characteristic.INTELLIGENT, Characteristic.PLAYFUL, Characteristic.ALERT))
                        .breedingDifficulty(Difficulty.BEGINNER)
                        .activityLevel(Level.MEDIUM)
                        .sheddingLevel(Level.LOW)
                        .spaceNeeds(Level.LOW)
                        .groomingNeeds(Level.LOW)
                        .healthIssues(Level.LOW)
                        .trainability(Level.HIGH)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.GERMAN_SHORTHAIRED_POINTER)
                        .shortDescription("Wszechstronny i aktywny")
                        .description("German Shorthaired Pointer to wszechstronny pies myśliwski o energicznym temperamencie.")
                        .imageUrl("https://static.vecteezy.com/system/resources/previews/024/107/852/non_2x/dog-sitting-on-a-transparent-background-ai-generated-png.png")
                        .originCountry("Niemcy")
                        .height(62.0f)
                        .weight(27.0f)
                        .lifeSpan(new RangeObject(10, 12))
                        .price(new RangeObject(3500, 6000))
                        .colors(List.of(Color.BROWN, Color.WHITE))
                        .characteristics(List.of(Characteristic.ENERGETIC, Characteristic.INTELLIGENT, Characteristic.LOYAL))
                        .breedingDifficulty(Difficulty.ADVANCED)
                        .activityLevel(Level.HIGH)
                        .sheddingLevel(Level.MEDIUM)
                        .spaceNeeds(Level.HIGH)
                        .groomingNeeds(Level.LOW)
                        .healthIssues(Level.MEDIUM)
                        .trainability(Level.HIGH)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.YORKSHIRE_TERRIER)
                        .shortDescription("Mały, ale odważny")
                        .description("Yorkshire Terrier to mały pies o dużej odwadze i eleganckim wyglądzie.")
                        .imageUrl("https://png.pngtree.com/png-clipart/20231014/original/pngtree-yorkshire-terrier-dog-isolated-png-image_13300537.png")
                        .originCountry("Anglia")
                        .height(20.0f)
                        .weight(3.0f)
                        .lifeSpan(new RangeObject(13, 16))
                        .price(new RangeObject(2500, 5000))
                        .colors(List.of(Color.BLACK, Color.TAN))
                        .characteristics(List.of(Characteristic.BRAVE, Characteristic.PLAYFUL, Characteristic.ALERT))
                        .breedingDifficulty(Difficulty.BEGINNER)
                        .activityLevel(Level.LOW)
                        .sheddingLevel(Level.LOW)
                        .spaceNeeds(Level.LOW)
                        .groomingNeeds(Level.HIGH)
                        .healthIssues(Level.MEDIUM)
                        .trainability(Level.MEDIUM)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(true)
                        .build(),
                Dog.builder()
                        .breed(Breed.BOXER)
                        .shortDescription("Energiczny i lojalny")
                        .description("Boxer to energiczny i lojalny pies rodzinny, który uwielbia zabawę.")
                        .imageUrl("https://png.pngtree.com/png-clipart/20230506/original/pngtree-boxer-dog-on-white-background-png-image_9145514.png")
                        .originCountry("Niemcy")
                        .height(63.0f)
                        .weight(30.0f)
                        .lifeSpan(new RangeObject(10, 12))
                        .price(new RangeObject(3000, 5500))
                        .colors(List.of(Color.FAWN, Color.BRINDLE, Color.WHITE))
                        .characteristics(List.of(Characteristic.FRIENDLY, Characteristic.ENERGETIC, Characteristic.BRAVE))
                        .breedingDifficulty(Difficulty.INTERMEDIATE)
                        .activityLevel(Level.HIGH)
                        .sheddingLevel(Level.MEDIUM)
                        .spaceNeeds(Level.HIGH)
                        .groomingNeeds(Level.LOW)
                        .healthIssues(Level.HIGH)
                        .trainability(Level.HIGH)
                        .goodWithChildren(true)
                        .goodWithOtherPets(false)
                        .hypoallergenic(false)
                        .build()
        );

        dogRepository.saveAll(dogs);
    }
}
