package org.pk.edog.seeder;

import org.pk.edog.model.custom.RangeObject;
import org.pk.edog.model.entity.Dog;
import org.pk.edog.model.enums.*;
import org.pk.edog.repository.DogRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public class DogSeeder implements CommandLineRunner {

    private final DogRepository dogRepository;

    public DogSeeder(DogRepository dogRepository) {
        this.dogRepository = dogRepository;
    }

    @Override
    public void run(String... args) {
        dogRepository.deleteAll();

        // Create sample dogs
        List<Dog> dogs = List.of(
                Dog.builder()
                        .breed(Breed.LABRADOR_RETRIEVER)
                        .shortDescription("Przyjazny i towarzyski")
                        .description("Labrador Retriever to przyjazna i towarzyska rasa.")
                        .imageUrl("https://www.dogster.com/wp-content/uploads/2024/04/labrador-retriever-dog-standing-in-the-grass_Alexander-Rim_Shutterstock.jpg")
                        .originCountry("Kanada")
                        .height(55.0f)
                        .weight(30.0f)
                        .lifeSpan(new RangeObject(15, 18))
                        .price(new RangeObject(3000, 4000))
                        .colors(List.of(Color.BLACK, Color.CREAM, Color.WHITE))
                        .characteristics(List.of(Characteristic.FRIENDLY, Characteristic.ENERGETIC,
                                Characteristic.CONFIDENT, Characteristic.PLAYFUL))
                        .breedingDifficulty(Difficulty.BEGINNER)
                        .activityLevel(Level.HIGH)
                        .sheddingLevel(Level.MEDIUM)
                        .spaceNeeds(Level.MEDIUM)
                        .groomingNeeds(Level.LOW)
                        .healthIssues(Level.MEDIUM)
                        .trainability(Level.HIGH)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.GERMAN_SHEPHERD)
                        .shortDescription("Pewny siebie i odważny")
                        .description("Owczarek niemiecki to pewna siebie i odważna rasa.")
                        .imageUrl("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTn4ir7qxd2_RlqMp6l12zjeLI_EE3sO1ulMZYDrHrlN-x2SbHu")
                        .originCountry("Niemcy")
                        .height(60.0f)
                        .weight(35.0f)
                        .lifeSpan(new RangeObject(14, 18))
                        .price(new RangeObject(2000, 3000))
                        .colors(List.of(Color.BLACK, Color.TAN, Color.SABLE))
                        .characteristics(List.of(Characteristic.CONFIDENT, Characteristic.INTELLIGENT,
                                Characteristic.ACTIVE, Characteristic.ENERGETIC))
                        .breedingDifficulty(Difficulty.BEGINNER)
                        .activityLevel(Level.HIGH)
                        .sheddingLevel(Level.HIGH)
                        .spaceNeeds(Level.HIGH)
                        .groomingNeeds(Level.MEDIUM)
                        .healthIssues(Level.HIGH)
                        .trainability(Level.HIGH)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.GOLDEN_RETRIEVER)
                        .shortDescription("Inteligentny i przyjazny")
                        .description("Golden Retriever to inteligentna i przyjazna rasa.")
                        .imageUrl("https://www.miesodlapsow.pl/uploads/blog/main/64f846347c8fe-2-1200x750.jpg")
                        .originCountry("Szkocja")
                        .height(55.0f)
                        .weight(30.0f)
                        .lifeSpan(new RangeObject(16, 18))
                        .price(new RangeObject(2500, 3500))
                        .colors(List.of(Color.GOLDEN))
                        .characteristics(List.of(Characteristic.INTELLIGENT, Characteristic.FRIENDLY, Characteristic.ACTIVE))
                        .breedingDifficulty(Difficulty.INTERMEDIATE)
                        .activityLevel(Level.HIGH)
                        .sheddingLevel(Level.HIGH)
                        .spaceNeeds(Level.MEDIUM)
                        .groomingNeeds(Level.MEDIUM)
                        .healthIssues(Level.MEDIUM)
                        .trainability(Level.HIGH)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.FRENCH_BULLDOG)
                        .shortDescription("Grzeczny i zabawny")
                        .description("Buldog francuski jest zabawną i łatwą w hodowli rasą")
                        .imageUrl("https://imageserver.petsbest.com/marketing/blog/french-bulldog.jpg")
                        .originCountry("Francja")
                        .height(30.0f)
                        .weight(12.0f)
                        .lifeSpan(new RangeObject(12, 16))
                        .price(new RangeObject(2500, 4000))
                        .colors(List.of(Color.BRINDLE, Color.FAWN, Color.TRI_COLOR))
                        .characteristics(List.of(Characteristic.CALM, Characteristic.PLAYFUL, Characteristic.SHY,
                                Characteristic.GENTLE))
                        .breedingDifficulty(Difficulty.ADVANCED)
                        .activityLevel(Level.LOW)
                        .sheddingLevel(Level.LOW)
                        .spaceNeeds(Level.LOW)
                        .groomingNeeds(Level.LOW)
                        .healthIssues(Level.HIGH)
                        .trainability(Level.MEDIUM)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.BULLDOG)
                        .shortDescription("Potulny i chętny do działania")
                        .description("Buldog to potulna i pełna chęci do działania rasa.")
                        .imageUrl("https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Bulldog_inglese.jpg/640px-Bulldog_inglese.jpg")
                        .originCountry("Anglia")
                        .height(40.0f)
                        .weight(25.0f)
                        .lifeSpan(new RangeObject(16, 18))
                        .price(new RangeObject(2000, 3000))
                        .colors(List.of(Color.BRINDLE, Color.WHITE))
                        .characteristics(List.of(Characteristic.PROTECTIVE, Characteristic.ALERT,
                                Characteristic.CONFIDENT))
                        .breedingDifficulty(Difficulty.ADVANCED)
                        .activityLevel(Level.LOW)
                        .sheddingLevel(Level.MEDIUM)
                        .spaceNeeds(Level.LOW)
                        .groomingNeeds(Level.LOW)
                        .healthIssues(Level.HIGH)
                        .trainability(Level.MEDIUM)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.POODLE)
                        .shortDescription("Aktywny i czujny")
                        .description("Pudel to aktywna i czujna rasa.")
                        .imageUrl("https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSNjuHGCKw2oq4FYvK9VdxsudFF0txgPq1P54q1HReutbOs5oT1")
                        .originCountry("Niemcy")
                        .height(45.0f)
                        .weight(20.0f)
                        .lifeSpan(new RangeObject(16, 20))
                        .price(new RangeObject(2000, 5000))
                        .colors(List.of(Color.WHITE, Color.BLACK, Color.BROWN))
                        .characteristics(List.of(Characteristic.ACTIVE, Characteristic.ALERT,
                                Characteristic.PLAYFUL, Characteristic.INTELLIGENT))
                        .breedingDifficulty(Difficulty.BEGINNER)
                        .activityLevel(Level.HIGH)
                        .sheddingLevel(Level.LOW)
                        .spaceNeeds(Level.MEDIUM)
                        .groomingNeeds(Level.HIGH)
                        .healthIssues(Level.MEDIUM)
                        .trainability(Level.HIGH)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(true)
                        .build(),
                Dog.builder()
                        .breed(Breed.BEAGLE)
                        .shortDescription("Ciekawski i wesoły")
                        .description("Beagle to ciekawska i wesoła rasa.")
                        .imageUrl("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQATF9rXor1M4e-wU0TPwZ2ueVRmYHzKqMxYwhatd7qI5Jwl7B4")
                        .originCountry("Anglia")
                        .height(35.0f)
                        .weight(15.0f)
                        .lifeSpan(new RangeObject(14, 18))
                        .price(new RangeObject(2000, 4000))
                        .colors(List.of(Color.FAWN))
                        .characteristics(List.of(Characteristic.CURIOUS, Characteristic.CALM,
                                Characteristic.CONFIDENT, Characteristic.FRIENDLY))
                        .breedingDifficulty(Difficulty.INTERMEDIATE)
                        .activityLevel(Level.HIGH)
                        .sheddingLevel(Level.MEDIUM)
                        .spaceNeeds(Level.MEDIUM)
                        .groomingNeeds(Level.LOW)
                        .healthIssues(Level.MEDIUM)
                        .trainability(Level.HIGH)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.ROTTWEILER)
                        .shortDescription("Lojalny i pewny siebie")
                        .description("Rottweiler to lojalna i pewna siebie rasa.")
                        .imageUrl("https://zooart.com.pl/blog/wp-content/uploads/2020/09/pies-rottweiler-3.png")
                        .originCountry("Niemcy")
                        .height(65.0f)
                        .weight(50.0f)
                        .lifeSpan(new RangeObject(15, 18))
                        .price(new RangeObject(3000, 6000))
                        .colors(List.of(Color.BLACK, Color.TAN))
                        .characteristics(List.of(Characteristic.LOYAL, Characteristic.CONFIDENT, Characteristic.ACTIVE,
                                Characteristic.STUBBORN, Characteristic.PROTECTIVE))
                        .breedingDifficulty(Difficulty.INTERMEDIATE)
                        .activityLevel(Level.HIGH)
                        .sheddingLevel(Level.HIGH)
                        .spaceNeeds(Level.HIGH)
                        .groomingNeeds(Level.MEDIUM)
                        .healthIssues(Level.HIGH)
                        .trainability(Level.HIGH)
                        .goodWithChildren(false)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.DACHSHUND)
                        .shortDescription("Żywy i odważny")
                        .description("Jamnik to żywa i odważna rasa.")
                        .imageUrl("https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRcm7pw5E1Y_AHdhIf0SfAyoahud7cIjN4GXntNOUjWVa8kKlXR")
                        .originCountry("Niemcy")
                        .height(25.0f)
                        .weight(10.0f)
                        .lifeSpan(new RangeObject(14, 18))
                        .price(new RangeObject(1500, 4000))
                        .colors(List.of(Color.BLACK, Color.TAN))
                        .characteristics(List.of(Characteristic.ENERGETIC, Characteristic.PLAYFUL,
                                Characteristic.STUBBORN, Characteristic.ALERT))
                        .breedingDifficulty(Difficulty.INTERMEDIATE)
                        .activityLevel(Level.MEDIUM)
                        .sheddingLevel(Level.LOW)
                        .spaceNeeds(Level.LOW)
                        .groomingNeeds(Level.LOW)
                        .healthIssues(Level.MEDIUM)
                        .trainability(Level.HIGH)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.PEMBROKE_WELSH_CORGI)
                        .shortDescription("Pogodny i przyjacielski")
                        .description("Pembroke Welsh Corgi to pogodna i przyjacielska rasa psa.")
                        .imageUrl("https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTljTEC7O8OjiuyjE__jmWhoC1yqk9AqnDtd2SEyFB6ZotrdyB57kl-zdzo2hUg0RP4DR1AQCqmfxsVjeFdK_bcVw")
                        .originCountry("Walia")
                        .height(30.0f)
                        .weight(12.0f)
                        .lifeSpan(new RangeObject(12, 15))
                        .price(new RangeObject(2500, 3500))
                        .colors(List.of(Color.RED, Color.WHITE))
                        .characteristics(List.of(Characteristic.INTELLIGENT, Characteristic.PLAYFUL, Characteristic.FRIENDLY))
                        .breedingDifficulty(Difficulty.INTERMEDIATE)
                        .activityLevel(Level.MEDIUM)
                        .sheddingLevel(Level.HIGH)
                        .spaceNeeds(Level.MEDIUM)
                        .groomingNeeds(Level.LOW)
                        .healthIssues(Level.MEDIUM)
                        .trainability(Level.HIGH)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.SIBERIAN_HUSKY)
                        .shortDescription("Energiczny i przyjacielski")
                        .description("Syberyjski Husky to energiczna i przyjacielska rasa psa.")
                        .imageUrl("https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQphjPgQniDbLD-wD8dk1ds_F2jyEPNe4Fzm6BG6GGrrS0tuQh5nwihp1IsGFJT0GOzRvp2T4ZZAVV2iSOJCup7CA")
                        .originCountry("Rosja")
                        .height(55.0f)
                        .weight(23.0f)
                        .lifeSpan(new RangeObject(12, 14))
                        .price(new RangeObject(3000, 4000))
                        .colors(List.of(Color.WHITE, Color.BLACK))
                        .characteristics(List.of(Characteristic.ACTIVE, Characteristic.FRIENDLY, Characteristic.ENERGETIC))
                        .breedingDifficulty(Difficulty.ADVANCED)
                        .activityLevel(Level.HIGH)
                        .sheddingLevel(Level.HIGH)
                        .spaceNeeds(Level.HIGH)
                        .groomingNeeds(Level.MEDIUM)
                        .healthIssues(Level.MEDIUM)
                        .trainability(Level.MEDIUM)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.GREAT_DANE)
                        .shortDescription("Łagodny olbrzym")
                        .description("Dog niemiecki to łagodny i majestatyczny olbrzym.")
                        .imageUrl("https://image.petmd.com/files/styles/978x550/public/2024-06/great-dane.jpg?w=1080&q=75")
                        .originCountry("Niemcy")
                        .height(80.0f)
                        .weight(70.0f)
                        .lifeSpan(new RangeObject(8, 10))
                        .price(new RangeObject(4000, 6000))
                        .colors(List.of(Color.BLACK, Color.WHITE, Color.BLUE))
                        .characteristics(List.of(Characteristic.GENTLE, Characteristic.FRIENDLY, Characteristic.LOYAL))
                        .breedingDifficulty(Difficulty.INTERMEDIATE)
                        .activityLevel(Level.MEDIUM)
                        .sheddingLevel(Level.MEDIUM)
                        .spaceNeeds(Level.HIGH)
                        .groomingNeeds(Level.LOW)
                        .healthIssues(Level.HIGH)
                        .trainability(Level.HIGH)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.DOBERMAN_PINSCHER)
                        .shortDescription("Lojalny i czujny")
                        .description("Doberman to lojalna i czujna rasa psa.")
                        .imageUrl("https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQ9kKIi1dCr4fB5WmWBfscnFvO-sbKs9u_TeSlpGfXBJ37_XUI-2fDj60dhaRLet-ZNPUDZdYnNTGX-j76wBjzOKw")
                        .originCountry("Niemcy")
                        .height(65.0f)
                        .weight(40.0f)
                        .lifeSpan(new RangeObject(10, 12))
                        .price(new RangeObject(3500, 5000))
                        .colors(List.of(Color.BLACK, Color.TAN))
                        .characteristics(List.of(Characteristic.PROTECTIVE, Characteristic.CONFIDENT, Characteristic.ACTIVE))
                        .breedingDifficulty(Difficulty.ADVANCED)
                        .activityLevel(Level.HIGH)
                        .sheddingLevel(Level.MEDIUM)
                        .spaceNeeds(Level.MEDIUM)
                        .groomingNeeds(Level.LOW)
                        .healthIssues(Level.MEDIUM)
                        .trainability(Level.HIGH)
                        .goodWithChildren(true)
                        .goodWithOtherPets(false)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.AUSTRALIAN_SHEPHERD)
                        .shortDescription("Inteligentny i pracowity")
                        .description("Owczarek australijski to inteligentna i pracowita rasa psa.")
                        .imageUrl("https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcR0Ea4vaSMJkZyJUXuz405aiqjfuiD4DW3ySlMdj59dgSiPQV7MDWnkKVAiVD9eUBP_6tXNOIinmr7r5WDwMhrrLw")
                        .originCountry("Stany Zjednoczone")
                        .height(50.0f)
                        .weight(25.0f)
                        .lifeSpan(new RangeObject(12, 15))
                        .price(new RangeObject(3000, 4500))
                        .colors(List.of(Color.BLUE, Color.RED, Color.MERLE))
                        .characteristics(List.of(Characteristic.INTELLIGENT, Characteristic.ACTIVE, Characteristic.PLAYFUL))
                        .breedingDifficulty(Difficulty.INTERMEDIATE)
                        .activityLevel(Level.HIGH)
                        .sheddingLevel(Level.HIGH)
                        .spaceNeeds(Level.HIGH)
                        .groomingNeeds(Level.MEDIUM)
                        .healthIssues(Level.MEDIUM)
                        .trainability(Level.HIGH)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                        .build(),
                Dog.builder()
                        .breed(Breed.SHIH_TZU)
                        .shortDescription("Towarzyski i czuły")
                        .description("Shih Tzu to towarzyska i czuła rasa psa.")
                        .imageUrl("https://johndog.pl/wp-content/uploads/2017/02/pies-rasy-shih-tzu.jpg")
                        .originCountry("Chiny")
                        .height(25.0f)
                        .weight(7.0f)
                        .lifeSpan(new RangeObject(10, 16))
                        .price(new RangeObject(2000, 4000))
                        .colors(List.of(Color.WHITE, Color.GOLDEN, Color.BROWN))
                        .characteristics(List.of(Characteristic.CALM, Characteristic.GENTLE, Characteristic.FRIENDLY))
                        .breedingDifficulty(Difficulty.BEGINNER)
                        .activityLevel(Level.LOW)
                        .sheddingLevel(Level.LOW)
                        .spaceNeeds(Level.LOW)
                        .groomingNeeds(Level.HIGH)
                        .healthIssues(Level.MEDIUM)
                        .trainability(Level.MEDIUM)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(true)
                        .build(),
                Dog.builder()
                        .breed(Breed.MINIATURE_SCHNAUZER)
                        .shortDescription("Czujny i inteligentny")
                        .description("Miniaturowy sznaucer to czujna i inteligentna rasa psa.")
                        .imageUrl("https://www.metlifepetinsurance.com/content/dam/metlifecom/us/metlifepetinsurance/images/blog/Thumbnails/breed-spotlight/miniature-schnauzer-image-min.webp")
                        .originCountry("Niemcy")
                        .height(35.0f)
                        .weight(8.0f)
                        .lifeSpan(new RangeObject(12, 15))
                        .price(new RangeObject(2000, 3500))
                        .colors(List.of(Color.BLACK, Color.GREY))
                        .characteristics(List.of(Characteristic.ACTIVE, Characteristic.FRIENDLY, Characteristic.INTELLIGENT))
                        .breedingDifficulty(Difficulty.INTERMEDIATE)
                        .activityLevel(Level.MEDIUM)
                        .sheddingLevel(Level.LOW)
                        .spaceNeeds(Level.MEDIUM)
                        .groomingNeeds(Level.HIGH)
                        .healthIssues(Level.MEDIUM)
                        .trainability(Level.HIGH)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(true)
                        .build(),
                Dog.builder()
                        .breed(Breed.CAVALIER_KING_CHARLES_SPANIEL)
                        .shortDescription("Czuły i delikatny")
                        .description("Cavalier King Charles Spaniel to czuła i delikatna rasa psa.")
                        .imageUrl("https://media.os.fressnapf.com/cms/2020/07/ratgeber_hund_rasse_portraits_cavalier-king-charles-spaniel_1200x527.jpg?t=seoimg_703")
                        .originCountry("Anglia")
                        .height(30.0f)
                        .weight(8.0f)
                        .lifeSpan(new RangeObject(10, 15))
                        .price(new RangeObject(2500, 4000))
                        .colors(List.of(Color.RED, Color.WHITE))
                        .characteristics(List.of(Characteristic.GENTLE, Characteristic.FRIENDLY, Characteristic.PLAYFUL))
                        .breedingDifficulty(Difficulty.INTERMEDIATE)
                        .activityLevel(Level.LOW)
                        .sheddingLevel(Level.MEDIUM)
                        .spaceNeeds(Level.LOW)
                        .groomingNeeds(Level.MEDIUM)
                        .healthIssues(Level.MEDIUM)
                        .trainability(Level.HIGH)
                        .goodWithChildren(true)
                        .goodWithOtherPets(true)
                        .hypoallergenic(false)
                .build()
        );

        dogRepository.saveAll(dogs);
    }
}
